---
- name: "Datadog Agent | Official Install"
  ansible.builtin.import_role:
    name: datadog.datadog
  vars:
    # Hack to force become on imported tasks since import/include don't support become
    ansible_become: true
    datadog_enabled: true
    datadog_api_key: "{{ datadog_agent_env_vars.DD_API_KEY | mandatory }}"
    datadog_site: "{{ datadog_agent_env_vars.DD_SITE | default('datadoghq.com') }}"
    datadog_agent_major_version: "7"
    datadog_config:
      env: "{{ datadog_agent_env_vars.DD_ENV | default('youshouldsetthis') }}"
      tags: "{{ datadog_agent_env_vars.DD_TAGS | default([]) }}"
      log_level: "info"
      inventories_configuration_enabled: true
      inventories_checks_configuration_enabled: true
      process_config:
        process_collection:
          enabled: true
        container_collection:
          enabled: true
        process_discovery:
          enabled: true
          interval: 4h
          custom_sensitive_words: []
      logs_enabled: true
      logs_config:
        container_collect_all: true
        processing_rules: []
        compression_level: 6
      apm_config:
        enabled: true
        apm_non_local_traffic: false
        obfuscation: {}
        filter_tags:
          require: []
          reject: []
        ignore_resources: []
      otlp_config:
        receiver:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
              transport: tcp
            http:
              endpoint: 0.0.0.0:4318
      network_devices:
        snmp_traps:
          enabled: true
          port: 9162
          community_strings: []
          users: []
          bind_host: "0.0.0.0"
        netflow:
          enabled: true
          listeners: []
      snmp_listener:
        configs: []
      compliance_config:
        enabled: true

    network_config:
      enabled: true
    service_monitoring_config:
      enabled: false
    runtime_security_config:
      enabled: true
      fim_enabled: true
      network:
        enabled: true
      custom_sensitive_words: []
    system_probe_config:
      data_streams_config:
        enabled: true
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ["ssh", "sshd"]
      # ssh_check:
      #   init_config:
      #   instances:
      #     - host: localhost
      #       port: 22
      #       username: root
      #       password: <YOUR_PASSWORD>
      #       sftp_check: true
      #       private_key_file:
      #       add_missing_keys: true

- name: "Datadog Agent | Restart"
  ansible.builtin.service:
    name: datadog-agent
    enabled: true
    state: restarted
