# -*- mode: ruby -*-
# vi: set ft=ruby :

DEFAULT_VECTOR_ENV = {}
RUNTIME_VECTOR_ENV = DEFAULT_VECTOR_ENV.merge(ENV).select { |k, v| k.start_with?('DD_') }

BOXES = [
    {
        name: "ubuntu2004",
        hostname: "ubuntu2004",
        box: "ubuntu/focal64"
    },
    # {
    #     name: "ubuntu1804",
    #     hostname: "ubuntu1804",
    #     box: "ubuntu/bionic64"
    # },
    # {
    #     name: "centos8",
    #     hostname: "centos8",
    #     box: "centos/8"
    # },
    # {
    #     name: "centoss8",
    #     hostname: "centoss8",
    #     box: "centos/stream8"
    # },
    # {
    #     name: "centos7",
    #     hostname: "centos7",
    #     box: "centos/7"
    # },
]

Vagrant.configure("2") do |vagrant|
    BOXES.each do |config|
        vagrant.vm.define config[:name] do |machine|
            machine.vm.box = config[:box]
            machine.vm.hostname = config[:hostname]
            machine.vm.provider "virtualbox" do |vb|
                vb.name = config[:hostname]
                vb.cpus = 2
                vb.memory = "1024"
                vb.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
              end
            machine.vm.provision :ansible do |ansible|
                ansible.playbook = "provisioning/ansible/playbook.yaml"
                ansible.verbose = "v"
                ansible.extra_vars = {
                    vagrant: {
                        vector: {
                            env: RUNTIME_VECTOR_ENV,
                        }
                    }
                }
            end
        end
    end
end
