Vagrant.require_version '>= 2.0.0'

Vagrant.configure("2") do |config|
  # config.vm.provider "virtualbox" do |vb|
  # end
  # config.vm.provider "vmware_desktop" do |vb|
  # end
  # config.vm.provider "qemu" do |vb|
  # end
end