Vagrant.require_version '>= 2.0.0'

Vagrant.configure("2") do |config|
  config.vm.provider "vmware_desktop" do |p|
  end
  config.vm.provider "virtualbox" do |p|
  end
  # Requires vagrant-libvirt plugin
  # vagrant plugin install vagrant-libvirt
  # https://vagrant-libvirt.github.io/vagrant-libvirt/
  # config.vm.provider "libvirt" do |p|
  # end
  # Requires vagrant-parallels plugin
  # vagrant plugin install vagrant-parallels
  # https://parallels.github.io/vagrant-parallels/
  # config.vm.provider "parallels" do |p|
  # end
end