# -*- mode: ruby -*-
# vi: set ft=ruby :

# You can pass env variables when calling Vagrant. Current options from the Ansible playbook
# * ANSIBLE_USER_PASSWORD: "ansible"
# * DD_SITE: "datadoghq.com"
# * DD_ENV: "test"
# * DD_TAGS: "[datacenter:local]" - Must be a valid yaml list [a:b, c:d]. Used in the official role
# * DD_HOST_TAGS: "env:test,datacenter:local" - Comma separated. Used in the script installer

DEFAULT_VM_CONFIG = {
    cpu: {
        count: 2,
        execution_cap: 75,
    },
    memory: "1024",
    hostname: "set-this-on-each-box"
}
BOXES = [
    {
        name: "ubuntu2004",
        box: "ubuntu/focal64",
        vm: DEFAULT_VM_CONFIG.merge({
            hostname: "ubuntu2004.local",
        }),
    },
    {
        name: "ubuntu1804",
        box: "ubuntu/bionic64",
        vm: DEFAULT_VM_CONFIG.merge({
            hostname: "ubuntu1804.local",
        }),
    },
    # Currently the vector install fails due to a CA certifcate issue. Pretty sure Centos8 ships
    # old CAs
    # {
    #     name: "centos8",
    #     box: "centos/8",
    #     vm: DEFAULT_VM_CONFIG.merge({
    #         hostname: "centos8.local",
    #     }),
    # },
    # {
    #     name: "centoss8",
    #     box: "centos/stream8",
    #     vm: DEFAULT_VM_CONFIG.merge({
    #         hostname: "centoss8.local",
    #     }),
    # },
    # Currently the vector install fails due to a CA certifcate issue. Pretty sure Centos8 ships
    # old CAs
    # {
    #     name: "centos7",
    #     box: "centos/7",
    #     vm: DEFAULT_VM_CONFIG.merge({
    #         hostname: "centos7.local",
    #     }),
    # },
    # {
    #     name: "fedora37",
    #     box: "generic/fedora37",
    #     vm: DEFAULT_VM_CONFIG.merge({
    #         hostname: "fedora37.local",
    #     }),
    # },
]

Vagrant.configure("2") do |vagrant|
    BOXES.each_index do |box_index|
        config = BOXES[box_index]
        vagrant.vm.define config[:name] do |machine|
            machine.vm.box = config[:box]
            machine.vm.hostname = config[:vm][:hostname]
            machine.vm.network "private_network", ip: "172.17.1.#{box_index+100}"
            machine.vm.provider "virtualbox" do |vb|
                vb.name = config[:name]
                vb.cpus = config[:vm][:cpu][:count]
                vb.memory = config[:vm][:memory]
                vb.customize ["modifyvm", :id, "--cpuexecutioncap", "#{config[:vm][:cpu][:execution_cap]}"]
              end

            # Only provision the machines after the last VM is up and ready. This
            # let's us take advantage of Ansible's parallelism
            if box_index == BOXES.length - 1
                machine.vm.provision :ansible do |ansible|
                    ansible.playbook = "provisioning/ansible/playbook.yaml"
                    ansible.config_file = "provisioning/ansible/ansible.cfg"
                    ansible.limit = "all"
                    ansible.verbose = "v"
                    ansible.extra_vars = {
                        vagrant: {
                            datadog: {
                                install_agent: true,
                                install_agent_via_role: true,
                                install_agent_via_script: false,
                            },
                            vector: {
                                install_agent: true,
                            },
                        },
                    }
                end
            end
        end
    end
end
