version: '3'
services:
  datadog:
    container_name: datadog-agent
    image: gcr.io/datadoghq/agent:7
    # Requires 7.43.0 or newer
    environment:
      ## GLOBALS
      DD_HOSTNAME: <HOSTNAME>
      DD_API_KEY: <DD_API_KEY> # https://app.datadoghq.com/organization-settings/api-keys
      DD_ENV: sandbox # dev
      # DD_TAGS: "<tags>" # team:devops
      # DD_AC_EXCLUDE: name:datadog-agent # exclude this container from data collection
      ## TAGS https://docs.datadoghq.com/getting_started/tagging/assigning_tags/?tab=containerizedenvironments
      # DD_DOCKER_LABELS_AS_TAGS: '{"*":"%%label%%"}'
      ## LOGS https://docs.datadoghq.com/agent/docker/log/
      DD_LOGS_ENABLED: true
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: true
      DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION: true
      ## LIVE PROCESSES https://docs.datadoghq.com/graphing/infrastructure/process/?tab:docker
      DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED: true
      DD_PROCESS_CONFIG_CONTAINER_COLLECTION_ENABLED: true
      ## DOGSTATSD
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: true
      ## APM
      DD_APM_ENABLED: true
      DD_APM_NON_LOCAL_TRAFFIC: true
      ## Network Performance Monitoring.
      ## Running this on a Mac? Set this value to false
      DD_SYSTEM_PROBE_ENABLED: false
      # Inventories
      DD_INVENTORIES_CONFIGURATION_ENABLED: true
      DD_INVENTORIES_CHECKS_CONFIGURATION_ENABLED: true
      ###########
      ## PROXY ##
      ###########
      DD_DD_URL: http://haproxy:3834
      # DD_PROXY_HTTP: http://haproxy:3834
      # DD_PROXY_HTTPS: http://haproxy:3834
      # apm
      DD_APM_DD_URL: http://haproxy:3835
      # profiling
      DD_APM_PROFILING_DD_URL: http://haproxy:3836/api/v2/profile
      # debugger WIP
      # DD_APM_DEBUGGER_DD_URL: http://haproxy:<PORT>
      # telemetry
      DD_APM_TELEMETRY_DD_URL: http://haproxy:3843
      # process
      DD_PROCESS_CONFIG_PROCESS_DD_URL: http://haproxy:3837
      DD_PROCESS_CONFIG_EVENTS_DD_URL: http://haproxy:3848
      # logs
      DD_LOGS_CONFIG_LOGS_DD_URL: haproxy:3838 # Must not have scheme
      DD_LOGS_CONFIG_LOGS_NO_SSL: true
      DD_LOGS_CONFIG_FORCE_USE_HTTP: true
      # dbm metrics
      DD_DATABASE_MONITORING_METRICS_DD_URL: http://haproxy:3839
      DD_DATABASE_MONITORING_METRICS_LOGS_NO_SSL: true
      # dbm activity
      DD_DATABASE_MONITORING_ACTIVITY_DD_URL: http://haproxy:3839
      DD_DATABASE_MONITORING_ACTIVITY_LOGS_NO_SSL: true
      # dbm samples
      DD_DATABASE_MONITORING_SAMPLES_DD_URL: http://haproxy:3840
      DD_DATABASE_MONITORING_SAMPLES_LOGS_NO_SSL: true
      # ndm metadata
      DD_NETWORK_DEVICES_METADATA_DD_URL: http://haproxy:3841
      DD_NETWORK_DEVICES_METADATA_LOGS_NO_SSL: true
      # ndm traps
      DD_NETWORK_DEVICES_SNMP_TRAPS_FORWARDER_DD_URL: http://haproxy:3842
      DD_NETWORK_DEVICES_SNMP_TRAPS_FORWARDER_LOGS_NO_SSL: true
      # ndm netflow
      DD_NETWORK_DEVICES_NETFLOW_FORWARDER_DD_URL: http://haproxy:3847
      DD_NETWORK_DEVICES_NETFLOW_FORWARDER_LOGS_NO_SSL: true
      # orchestrator (cluster agent only)
      DD_ORCHESTRATOR_EXPLORER_ORCHESTRATOR_DD_URL: http://haproxy:3845
      # security (compliance) WIP
      # DD_COMPLIANCE_CONFIG_ENDPOINTS_DD_URL: http://haproxy:3834
      # DD_COMPLIANCE_CONFIG_ENDPOINTS_LOGS_NO_SSL: true
      # security (runtime) WIP
      # DD_RUNTIME_SECURITY_CONFIG_ENDPOINTS_DD_URL: http://haproxy:3846
      # DD_RUNTIME_SECURITY_CONFIG_ENDPOINTS_LOGS_NO_SSL: true

    depends_on:
      - haproxy
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - SYS_PTRACE
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
      - IPC_LOCK
      - CHOWN
    ports:
      - 127.0.0.1:8125:8125/udp # Dogstatsd
      - 127.0.0.1:8126:8126/tcp # APM
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /etc/passwd:/etc/passwd:ro # Live Processes
      - /sys/kernel/debug:/sys/kernel/debug # NPM
      - ./data/agent/conf.d:/conf.d:rw
      - ./data/logs:/data/logs:rw

    networks:
      - datadog-examples

  haproxy:
    build: "."
    # image: dd-haproxy
    container_name: dd-haproxy
    volumes:
      - ./data/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:rw
    networks:
      - datadog-examples

networks:
  datadog-examples: